---
name: KitPvp
version: 1.0
author: Adivius
main: Adivius\KitPvp\Main
api: 4.6.0
src-namespace-prefix: Adivius\KitPvp
depend:
  - BedrockEconomy

commands:
  kit:
    permission: adivius.kitpvp.kit
    description: "Choose a kit"
    usage: "/kit"
    aliases:
      - kits
  addkit:
    permission: adivius.kitpvp.kitmanager
    description: "Add a kit"
  removekit:
    permission: adivius.kitpvp.kitmanager
    description: "Remove a kit"
  reloadkits:
    permission: adivius.kitpvp.kitmanager
    description: "Read kits from the config"
  addbounty:
    permission: adivius.kitpvp.bounty
    description: "Change a persons bounty"
    usage: "/addbounty <player> <amount>"
  bounty:
    permission: adivius.kitpvp.bounty
    description: "See a persons bounty"
    usage: "/bounty <player>"

permissions:
  adivius.kitpvp.kit:
    description: "Permission for kits"
    default: true
  adivius.kitpvp.kit.others:
      description: "Send the kit form to a different player"
      default: op
  adivius.kitpvp.kitmanager:
    default: op
  adivius.kitpvp.bounty:
    default: true
...
