---
name: KitPvp
version: 3000
main: Adivius\KitPvp\Main
api: 4.6.0
src-namespace-prefix: Adivius\KitPvp

commands:
  spawn:
    permission: kits.kit
    description: "Teleport to spawn"
  clear:
    permission: kits.utils
    description: "Clears your inventory"
  rename:
    permission: kits.utils
    description: "Renames the item in your hand"
    usage: "/rename <name>"
  kit:
    permission: kits.kit
    description: "Choose a kit"
    usage: "/kit"
    aliases:
      - kits
  addkit:
    permission: kits.kitmanager
    description: "Add a kit"
  removekit:
    permission: kits.kitmanager
    description: "Remove a kit"
  updatefromconfig:
    permission: kits.kitmanager
    description: "Read kits from the config"
  getbalance:
    permission: kits.utils
    description: "Returns your balance"
  addbounty:
    permission: kits.bounty
    description: "Change a persons bounty"
    usage: "/addbounty <player> <amount>"
  bounty:
    permission: kits.bounty
    description: "See a persons bounty"
    usage: "/bounty <player>"

permissions:
  kits.utils:
    default: op
  kits.kit:
    description: "Permission for kits"
    default: true
  kits.kit.others:
      description: "Send others the kit form"
      default: op
  kits.kitmanager:
    default: op
  kits.bounty:
    default: true

...
